version: '3'
services:

  deakin-library:
    image: deakin-library
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: deakin-library
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://sit722week7task2_user:bkHGgvpSTmNlY1AKfgGe90QAok6bvAxj@dpg-cr76tupu0jms73af56rg-a.oregon-postgres.render.com/sit722week7task2
    restart: "no"

  deakin-inventory:
    image: deakin-inventory
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: deakin-inventory
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722week7task2_user:bkHGgvpSTmNlY1AKfgGe90QAok6bvAxj@dpg-cr76tupu0jms73af56rg-a.oregon-postgres.render.com/sit722week7task2
    restart: "no"
